main: fr.pederobien.minecraft.chat.ChatPlugin
name: minecraft-chat
version: 1.0_MC_1.16.5-SNAPSHOT
api-version: 1.16.5
depend: [minecraft-platform]

description:
commands:
  chatConfig:
    description: Command to create, delete update chat rooms
    permission: ChatPlugin.permission
  chatMsg:
    description: Command to send a message in a chat room.
    permission: chat.permission
  opMsg:
    description: Command to send a message to several chats
    permission: ChatPluging.permission

permissions:
  chat.permission:
    description: give access to command chat.
    default: true